// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bakery$0 from "../bakery/models.js";

/**
 * LocalEvent is one Run event this desktop's claude generated, with when it
 * generated it; the Transcript the frontend draws needs no more.
 */
export interface LocalEvent {
    "seq": number;
    "kind": string;
    "payload": json$0.RawMessage;
    "created_at": string;
}

/**
 * LocalRun is a Run this desktop executes right now: LocalRuns reports it so
 * the frontend draws its Transcript without a round trip to the Bakery.
 */
export interface LocalRun {
    "address": string;
    "guild": bakery$0.Named;
    "agent": bakery$0.RunAgent;
    "run_id": number;
    "issue": bakery$0.RunIssue | null;
    "invocation_source": string;
    "wake_reason": string;
    "wake_count": number;
    "status": string;
    "started_at": string;
    "events": LocalEvent[] | null;
}
