// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent is an Agent as the Bakery's agents context shows it
 * (services/api contexts/agents/http/agents.go), less what only the
 * dashboard uses to manage it.
 */
export interface Agent {
    "id": number;
    "name": string;
    "job": string;
    "job_label": string;
    "title": string;
    "icon": string;
    "capabilities": string;
    "status": string;
    "reports_to": Named | null;
    "hirer": Named | null;
    "roles": Role[] | null;
    "created_at": string;
    "terminated_at": string | null;
}

/**
 * Guild is one Guild the person is in.
 */
export interface Guild {
    "id": number;
    "name": string;
    "issue_prefix": string;
}

/**
 * Member is the person a Desktop key acts as.
 */
export interface Member {
    "id": number;
    "name": string;
    "email": string;
}

/**
 * Named is a Member or Agent the Bakery names by id.
 */
export interface Named {
    "id": number;
    "name": string;
}

/**
 * Role is a Role an Agent holds.
 */
export interface Role {
    "id": number;
    "name": string;
    "color": string;
    "position": number;
}
