// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * Agent is an Agent as the Bakery's agents context shows it
 * (services/api contexts/agents/http/agents.go), less what only the
 * dashboard uses to manage it.
 */
export interface Agent {
    "id": number;
    "name": string;
    "job": string;
    "job_label": string;
    "title": string;
    "icon": string;
    "capabilities": string;
    "status": string;
    "reports_to": Named | null;
    "hirer": Named | null;
    "roles": Role[] | null;
    "created_at": string;
    "terminated_at": string | null;
}

/**
 * Guild is one Guild the person is in.
 */
export interface Guild {
    "id": number;
    "name": string;
    "issue_prefix": string;
}

/**
 * Member is the person a Desktop key acts as.
 */
export interface Member {
    "id": number;
    "name": string;
    "email": string;
}

/**
 * Named is a Member or Agent the Bakery names by id.
 */
export interface Named {
    "id": number;
    "name": string;
}

/**
 * Role is a Role an Agent holds.
 */
export interface Role {
    "id": number;
    "name": string;
    "color": string;
    "position": number;
}

/**
 * Run is a Run as the Bakery's agents context shows it
 * (services/api contexts/agents/http/runs.go), for an Agent's Runs on its
 * page.
 */
export interface Run {
    "id": number;
    "agent": RunAgent;
    "issue": RunIssue | null;
    "invocation_source": string;
    "wake_reason": string;
    "wake_count": number;
    "status": string;
    "requested_by": Named | null;
    "desktop": Named | null;
    "retry_of_run_id": number | null;
    "usage": Usage;
    "exit_code": number | null;
    "error": string;
    "created_at": string;
    "started_at": string | null;
    "finished_at": string | null;
    "can_cancel": boolean;
}

/**
 * RunAgent is the Agent a Run is of.
 */
export interface RunAgent {
    "id": number;
    "name": string;
    "icon": string;
}

/**
 * RunEvent is one thing a Run's claude printed, numbered by Seq from 1.
 */
export interface RunEvent {
    "seq": number;
    "kind": string;
    "payload": json$0.RawMessage;
}

/**
 * RunIssue is the Issue a Run works on.
 */
export interface RunIssue {
    "id": number;
    "identifier": string;
    "title": string;
}

/**
 * Usage is a Run's usage as the claude CLI reported it; the cost is an
 * equivalent, never billed.
 */
export interface Usage {
    "input_tokens": number;
    "cached_input_tokens": number;
    "output_tokens": number;
    "turns": number;
    "cost_equivalent_usd": number;
    "duration_ms": number;
}
