ALTER TABLE nodes
  ADD COLUMN IF NOT EXISTS ssh_host TEXT,
  ADD COLUMN IF NOT EXISTS ssh_port INTEGER DEFAULT 22,
  ADD COLUMN IF NOT EXISTS ssh_user TEXT,
  ADD COLUMN IF NOT EXISTS ssh_public_key TEXT,
  ADD COLUMN IF NOT EXISTS ssh_private_key TEXT,
  ADD COLUMN IF NOT EXISTS ssh_fingerprint TEXT,
  ADD COLUMN IF NOT EXISTS ssh_last_connected TIMESTAMP WITH TIME ZONE;
