FROM oven/bun:latest

WORKDIR /app
COPY package.json bun.lockb*? ./
RUN bun --bun install --no-save

COPY . .

ENV PORT=3000
EXPOSE 3000

RUN bun run build || echo "No build script defined"

CMD ["bun", "run", "start"]
