// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Desktop holds every method the frontend calls. The Wails window binds it
 * (wails3 generate bindings turns its exported methods into
 * frontend/bindings), and `serve` exposes the same methods on /rpc, so both
 * transports run the same code.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Version answers the Desktop app's version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(753840120);
}
