// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Desktop holds every method the frontend calls. The Wails window binds it
 * (wails3 generate bindings turns its exported methods into
 * frontend/bindings), and `serve` exposes the same methods on /rpc, so both
 * transports run the same code.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bakery$0 from "./bakery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runner$0 from "./runner/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate makes the Bakery at address the one the window shows.
 */
export function Activate(address: string): $CancellablePromise<void> {
    return $Call.ByID(3058243509, address);
}

/**
 * Agent reads one Agent of the Guild guildID on the Bakery at address.
 */
export function Agent(address: string, guildID: number, id: number): $CancellablePromise<bakery$0.Agent> {
    return $Call.ByID(4187668381, address, guildID, id);
}

/**
 * Agents lists the Agents of the Guild guildID on the Bakery at address on
 * the tab status, and keeps them current with `agents` events while the
 * window shows them. It always asks the Bakery: only the shown tab is
 * refreshed, so the answer kept for another tab may be stale (an Agent
 * terminated while Paused was shown would still be under All).
 */
export function Agents(address: string, guildID: number, status: string): $CancellablePromise<bakery$0.Agent[] | null> {
    return $Call.ByID(3701220266, address, guildID, status);
}

/**
 * Bakeries lists the connected Bakeries, the active one marked.
 */
export function Bakeries(): $CancellablePromise<$models.ConnectedBakery[] | null> {
    return $Call.ByID(1470319212);
}

/**
 * CancelConnect cancels a pending connect on the Bakery and stops polling.
 */
export function CancelConnect(id: number): $CancellablePromise<void> {
    return $Call.ByID(1591542868, id);
}

/**
 * Connect starts a Desktop sign-in at address, opens its approve link in
 * the browser (in the window; in `serve` the page shows the link) and polls
 * it until it is approved, expired or cancelled. Every change is a
 * "connect" event and ConnectStatus's answer.
 */
export function Connect(address: string): $CancellablePromise<$models.ConnectStart> {
    return $Call.ByID(4076694394, address);
}

/**
 * ConnectStatus is where the connect id stands.
 */
export function ConnectStatus(id: number): $CancellablePromise<$models.ConnectState> {
    return $Call.ByID(906565636, id);
}

/**
 * Disconnect signs this Desktop out of the Bakery at address and forgets
 * its key, also when the sign-out fails (the Bakery unreachable, the key
 * already signed out), as Paperclip's logout does.
 */
export function Disconnect(address: string): $CancellablePromise<void> {
    return $Call.ByID(938215710, address);
}

/**
 * FollowRun starts following the Run id's stream in the Guild guildID, for
 * a Run this desktop did not claim, until UnfollowRun or the Run ends.
 * Idempotent: following the same Run again does nothing.
 */
export function FollowRun(address: string, guildID: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(3478328238, address, guildID, id);
}

/**
 * Guilds lists the person's Guilds on the Bakery at address, and keeps
 * them current with `guilds` events while the window shows them.
 */
export function Guilds(address: string): $CancellablePromise<bakery$0.Guild[] | null> {
    return $Call.ByID(28945796, address);
}

/**
 * Limit is when the Subscription limit this computer's claude login hit
 * resets, while it holds; nil when it does not, or no Runner runs here.
 */
export function Limit(): $CancellablePromise<string | null> {
    return $Call.ByID(1703823799);
}

/**
 * LocalRuns is the Runs this desktop executes right now, across every
 * connected Bakery, for the Agent page's live Transcript and "Runs on this
 * desktop" without a round trip to a Bakery: nil when this process runs no
 * Runner (`serve --no-runner`).
 */
export function LocalRuns(): $CancellablePromise<runner$0.LocalRun[] | null> {
    return $Call.ByID(407696129);
}

/**
 * Me is the person the Desktop key acts as on the Bakery at address.
 */
export function Me(address: string): $CancellablePromise<bakery$0.Member> {
    return $Call.ByID(2040295850, address);
}

/**
 * RunEvents answers the Run id's stored events after seq after, in the
 * Guild guildID: a final Run's Transcript, read once.
 */
export function RunEvents(address: string, guildID: number, id: number, after: number): $CancellablePromise<bakery$0.RunEvent[] | null> {
    return $Call.ByID(2910066680, address, guildID, id, after);
}

export function Runs(address: string, guildID: number, id: number): $CancellablePromise<bakery$0.Run[] | null> {
    return $Call.ByID(3789588182, address, guildID, id);
}

/**
 * UnfollowRun stops following the Run id's stream started by FollowRun.
 */
export function UnfollowRun(address: string, guildID: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(1781655771, address, guildID, id);
}

/**
 * Version answers the Desktop app's version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(753840120);
}
