// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./store/models.js";

/**
 * ConnectStart is what Connect answers: the link to approve this Desktop
 * in the browser.
 */
export interface ConnectStart {
    "id": number;
    "address": string;
    "approval_url": string;
    "expires_at": string;
}

/**
 * ConnectState is a connect's status; Error explains failed.
 */
export interface ConnectState {
    "id": number;
    "address": string;
    "status": string;
    "error"?: string;
}

/**
 * ConnectedBakery is one connected Bakery as the frontend sees it: never
 * its key.
 */
export interface ConnectedBakery {
    "address": string;
    "member": store$0.Member;
    "connected_at": string;
    "active": boolean;
    "signed_out": boolean;
}
