// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Member is the person a Bakery's Desktop key acts as.
 */
export interface Member {
    "id": number;
    "name": string;
    "email": string;
}
