<script lang="ts" module>
  // Lucide icons (ISC, see NOTICE) under the names the pages already use. Each
  // name maps to the icon Paperclip uses for that meaning (its Sidebar,
  // CompanySettingsSidebar and InstanceSidebar), or lucide's nearest one where
  // Paperclip has no such meaning.
  import {
    ArrowRight,
    ArrowUpDown,
    Boxes,
    CircleAlert,
    CircleCheck,
    CirclePlay,
    CircleStop,
    Check,
    ChevronDown,
    Code,
    Cpu,
    Database,
    Eraser,
    ExternalLink,
    Eye,
    EyeOff,
    FileText,
    Filter,
    FolderOpen,
    GitBranch,
    Globe,
    History,
    Info,
    KeyRound,
    LayoutDashboard,
    LayoutGrid,
    Layers,
    List,
    Lock,
    LogOut,
    Mail,
    MessageSquare,
    Network,
    Plus,
    RefreshCw,
    RotateCcw,
    Search,
    Server,
    Settings,
    ShieldAlert,
    Square,
    SquareTerminal,
    Terminal,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Upload,
    UserRound,
    Users,
    Variable,
    Bell,
    HardDrive,
    X,
  } from '@lucide/svelte'

  const icons = {
    'dashboard': LayoutDashboard,
    'projects': FolderOpen,
    'servers': Server,
    'storages': HardDrive,
    'notifications': Bell,
    'keys': KeyRound,
    'settings': Settings,
    'profile': UserRound,
    'teams': Users,
    'logout': LogOut,
    'search': Search,
    'lock': Lock,
    'plus': Plus,
    'x': X,
    'check': Check,
    'chevron-down': ChevronDown,
    'trash': Trash2,
    'external-link': ExternalLink,
    'alert-triangle': TriangleAlert,
    'alert-circle': CircleAlert,
    'check-circle': CircleCheck,
    'info-circle': Info,
    'refresh': RefreshCw,
    'restart': RotateCcw,
    'stop': Square,
    'play-circle': CirclePlay,
    'eye': Eye,
    'eye-off': EyeOff,
    'eye-off2': EyeOff,
    'browser-code': Code,
    'database': Database,
    'layers': Layers,
    'terminal': Terminal,
    'arrow-right': ArrowRight,
    'grid': LayoutGrid,
    'unordered-list': List,
    'globe': Globe,
    'filter': Filter,
    'sources': GitBranch,
    'variables': Variable,
    'time-back': History,
    'feedback': MessageSquare,
    'graph': TrendingUp,
    'broom': Eraser,
    'stop-circle': CircleStop,
    'cpu': Cpu,
    'shield-alert': ShieldAlert,
    'file-content': FileText,
    'sort-direction': ArrowUpDown,
    'upload': Upload,
    'browser-terminal': SquareTerminal,
    'mail': Mail,
    'destinations': Network,
    'code': Boxes,
  } as const

  export type IconName = keyof typeof icons
</script>

<script lang="ts">
  let { name, class: className = 'size-4' }: { name: IconName; class?: string } = $props()

  const Glyph = $derived(icons[name])
</script>

<Glyph class={className} aria-hidden="true" />
