<script lang="ts">
  // Paperclip's New skill wizard (NewSkillWizard in
  // ui/src/pages/CompanySkills.tsx; MIT, see NOTICE) on the dashboard's
  // Modal, shaped as NewRoutineDialog. Only its Basics (a name, the Skill
  // slug derived from it until edited, a description) and its Content (an
  // optional SKILL.md) are ported; its Design and Review steps style a
  // catalog card The Bakery does not have. A SKILL.md left empty is
  // generated by the API from the name and description.
  import { Input } from '@bakery/ui/components/ui/input'
  import { ApiError } from './api'
  import MarkdownField from './MarkdownField.svelte'
  import { go, skillPath } from './router.svelte'
  import { createSkill, skillSlug } from './skills'
  import Button from './ui/Button.svelte'
  import FieldError from './ui/FieldError.svelte'
  import Modal from './ui/Modal.svelte'
  import Textarea from './ui/Textarea.svelte'
  import { toast } from './ui/toast.svelte'

  let { open = $bindable(false) }: { open?: boolean } = $props()

  let name = $state('')
  let slug = $state('')
  let slugEdited = $state(false)
  let description = $state('')
  let markdown = $state('')
  let saving = $state(false)
  let errors = $state<Record<string, string>>({})
  let error = $state('')

  const shownSlug = $derived(slugEdited ? slug : skillSlug(name))

  function reset() {
    name = slug = description = markdown = error = ''
    slugEdited = false
    errors = {}
  }

  async function submit() {
    if (!name.trim() || saving) return
    saving = true
    errors = {}
    error = ''
    try {
      const skill = await createSkill({
        name: name.trim(),
        slug: shownSlug || undefined,
        description: description.trim() || undefined,
        markdown: markdown.trim() ? markdown : undefined,
      })
      toast.success('Skill created', skill.name)
      open = false
      reset()
      go(skillPath(skill.id))
    } catch (e) {
      if (e instanceof ApiError && Object.keys(e.errors).length) errors = e.errors
      else error = e instanceof Error ? e.message : String(e)
    } finally {
      saving = false
    }
  }
</script>

<Modal bind:open variant="none" title="New skill" subtitle="A skill is a package of instructions and files an agent loads when it runs." isLarge onclose={reset}>
  <div class="space-y-4">
    <label class="grid gap-1.5 text-sm font-medium">
      Name
      <!-- svelte-ignore a11y_autofocus -->
      <Input autofocus maxlength={100} placeholder="e.g. Release notes" bind:value={name} />
      <FieldError error={errors.name} />
    </label>
    <label class="grid gap-1.5 text-sm font-medium">
      Slug
      <Input
        maxlength={64}
        class="font-mono"
        value={shownSlug}
        oninput={(e) => {
          slug = e.currentTarget.value
          slugEdited = true
        }}
      />
      <span class="text-xs font-normal text-muted-foreground">The folder claude loads it from. It cannot change once the skill exists.</span>
      <FieldError error={errors.slug} />
    </label>
    <label class="grid gap-1.5 text-sm font-medium">
      Description
      <Textarea bind:value={description} rows={2} maxlength={1000} placeholder="When an agent should use this skill" />
      <FieldError error={errors.description} />
    </label>
    <div class="space-y-1.5">
      <MarkdownField bind:value={markdown} label="SKILL.md (optional)" placeholder="Leave empty to start from a generated SKILL.md" rows={8} onsubmit={submit} />
      <FieldError error={errors.markdown} />
    </div>
    {#if error}<p class="text-sm text-destructive">{error}</p>{/if}
  </div>
  {#snippet footer()}
    <Button variant="highlighted" disabled={!name.trim()} loading={saving} onclick={submit}>
      {saving ? 'Creating…' : 'Create skill'}
    </Button>
  {/snippet}
</Modal>
